config/routes.rb
Angelist::Application.routes.draw do
  
  resources :startups, :only => [:index, :show, :create, :update, :destroy] 
  
  root :to => 'startups#index'

end

app/models/startup.rb
class Startup < ActiveRecord::Base
  
  attr_accessible :company_id, :status, :company_name, :company_url, :angellist_profile, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  http_basic_authenticate_with :name => "Admin", :password => "Y0b1b1t"
  def index
    if params[:search].nil? || params[:search].blank?
      raw_list = AngellistApi.get_tag_startups(9217, {:page => params[:page], :per_page => 50, :order => "popularity"})
      @startups = raw_list.startups
    else
      @search_text = params[:search]
      search = AngellistApi.search(@search_text, {type: "Startup"})
      items = []
      search.each do |item| 
        items << item.id
      end
      if items.any?
        @startups = AngellistApi.get_startups(items)
      else
        @startups = []
      end
    end
    @startups.define_singleton_method(:total_pages) do
      return raw_list ? raw_list.last_page : 1
    end
    @startups.define_singleton_method(:current_page) do
      return raw_list ? raw_list.page : 1
    end
  end
  
  def show
    @startup = AngellistApi.get_startup(params[:id])
  end
  
  def create
    @startup = Startup.new(params[:startup])
    if @startup.save
      @created = true
    else
      @created = false
    end
  end
  
  def update
    @startup = Startup.find_by_company_id(params[:startup][:company_id])
    if @startup.update_attributes(params[:startup])
      @created = true
    else
      @created = false
    end
    
  end
  
  def destroy
    
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Angelist
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          =link_to "AngelList", root_path, :class => "brand"
          = form_tag startups_path, method: :get do
            = text_field_tag :search, @search_text, placeholder: "Search", class: "navbar-search pull-right"
            

    .container
      .row
        .span9
          = yield
        .span3
          .company-info
      

app/views/startups/_company_info.html.haml
.media
  = link_to image_tag(startup.thumb_url, {alt: "thumb", class: "media-object img-thumbnail"}), startup.company_url, target: "_blank", class: "pull-left"
  .media-body
    %h4.media-heading
      = startup.name
    - record = Startup.find_by_company_id(startup.id).present? ? Startup.find_by_company_id(startup.id) : Startup.new
    = simple_form_for record do |f|
      = f.input :company_id, :as => :hidden, :input_html => { :value => startup.id }
      = f.input :company_name, :as => :hidden, :input_html => { :value => startup.name }
      = f.input :company_url, :as => :hidden, :input_html => { :value => startup.company_url }
      = f.input :angellist_profile, :as => :hidden, :input_html => { :value => startup.angellist_url }
      = f.input :status, collection: [['Skipped', 1], ['Contacted', 2]], :label => false, :include_blank => "Select" , input_html: { class: 'status-input' }
%p
  = startup.product_desc

#companyCarousel.carousel.slide
  - if startup.video_url.present?
    - company_count = startup.screenshots.count + 1
  - else
    - company_count = startup.screenshots.count
  %ol.carousel-indicators
    - (0..(company_count - 1)).each do |i|
      %li{"data-target" => "companyCarousel", "data-slide-to" => "#{i}", class: "#{'active' if i == 0}"}
      
  .carousel-inner
    - (0..(company_count - 1)).each do |i|
      .item{class: "#{'active' if i == 0}"}
        
        - if startup.video_url.present? && i == 0 
          .video-item
            = link_to "Video", startup.video_url
        -else
          = link_to image_tag(startup.screenshots[i].thumb, {alt: "slider"}), startup.screenshots[i].original, :target => "_blank" unless startup.screenshots[i].nil?
        
  = link_to "#companyCarousel", "data-slide" => "prev", class: "carousel-control left" do
    &lsaquo;
  = link_to "#companyCarousel", "data-slide" => "next", class: "carousel-control right" do
    &rsaquo;
  
  

app/views/startups/create.js.erb
<% if @created %>
  $("table tr.company-<%= @startup.company_id %>").addClass("success");
<% else %>
  $("table tr.company-<%= @startup.company_id %>").addClass("error");
<% end %>

app/views/startups/index.html.haml
.companies-list
  %table.table.table-hover
    %thead
      %tr
        %th
        %th
          Name
        %th
          Description
        %th
          Quality
        %th
          Link
        %th
    - @startups.each do |startup|
      - record = Startup.find_by_company_id(startup.id).present? ? Startup.find_by_company_id(startup.id) : Startup.new
    
      - if startup.hidden == false
        %tr{class: "company-#{startup.id} #{'success' if record.company_id.present?}"}
          %td.logo.more-info
            = image_tag(startup.thumb_url, {alt: "logo", class: "img-logo"})
          %td.more-info
            = startup.name
          %td.more-info
            = startup.high_concept
          %td.more-info
            = startup.quality
          %td
            = link_to "AngelList", startup.angellist_url, :target => "_blank"
          %td
            = simple_form_for record do |f|
              = f.input :company_id, :as => :hidden, :input_html => { :value => startup.id }
              = f.input :company_name, :as => :hidden, :input_html => { :value => startup.name }
              = f.input :company_url, :as => :hidden, :input_html => { :value => startup.company_url }
              = f.input :angellist_profile, :as => :hidden, :input_html => { :value => startup.angellist_url }
              = f.input :status, collection: [['Skipped', 1], ['Contacted', 2]], :label => false, :include_blank => "Select" , input_html: { class: 'status-input' }
    
    
  = will_paginate @startups, :class => "pagination pagination-centered"

app/views/startups/show.js.erb
$(".company-info").html("<%= j render 'company_info', :startup => @startup %>");
$('.carousel').carousel();

$('document').ready(function(){
  $("div.video-item").embedly({key: "96d026f7d8fb4851948d8cb42bee1819", query: {maxwidth: 270}});

  	$("select.status-input").change(function(){
	  if ($(this).val() != "")
	  {
	 	  var currentFrom = $(this).closest("form");
	      var ajaxType = "POST";
	      if ($(currentFrom).attr("id").indexOf("edit") != -1)
	      {
		    ajaxType = "PUT"
	      }
	      $.ajax({
	        url: escape($(currentFrom).attr('action')),
	        cache: false,
	        data: $(currentFrom).serialize(),
	        dataType: "script",
	        type: ajaxType
	      });
	  }
	});
});

app/views/startups/update.js.erb
<% if @created %>
  $("table tr.company-<%= @startup.company_id %>").addClass("success");
<% else %>
  $("table tr.company-<%= @startup.company_id %>").addClass("error");
<% end %>